config/routes.rb
Rails.application.routes.draw do



  namespace :admin do
    get 'tags/new'
  end
  devise_for :anglers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_scope :angler do
    post 'public/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end
  

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    root to: 'homes#top'
    resources :fishing_successes, only: [:index, :show, :destroy]
    resources :anglers, only: [:index, :show, :destroy]
    resources :comments, only: [:destroy]
    resources :tags, only: [:new, :create, :destroy]
  end


  scope module: :public do
    root to: 'homes#top'
    get 'search'=>'fishing_successes#search'
    resources :fishing_successes, only: [:index, :show, :new, :create, :destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    get 'anglers/favorites'=>'anglers#my_favorite'
    get 'anglers/fishing_successes'=>'anglers#my_post'
    get 'anglers/mypage'=>"anglers#show"
    get 'anglers/information/edit'=>"anglers#edit"
    get 'anglers/withdrawal/verification'=>"anglers#verification"
    patch 'anglers/information'=>"anglers#update"
    delete 'anglers/withdrawal'=>"anglers#destroy"
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
    @comments = Comment.page(params[:page]).per(10).order(created_at: :desc)
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/views/admin/homes/top.html.erb
<div class="container">
  <div class="row my-4">
    <div class="col text-center mt-3 fs-4">
      コメント一覧
    </div>
  </div>
  <div class="row justify-content-center mx-5">
    <div class="col-10">
      <table class="table table-hover table-inverse" width="100%">
        <thead class="table-secondary">
          <tr>
            <th>日時</th>
            <th>氏名</th>
            <th>コメント</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @comments.each do |comment| %>
            <tr>
              <td>
                <%= comment.created_at.strftime("%m月%d日") %>
              </td>
              <td>
                <%= link_to admin_angler_path(comment.angler), class: "text-dark" do %>
                  <%= comment.angler.name %>
                <% end %>
              </td>
              <td>
                <%= truncate(comment.content, :length => 28) %>
              </td>
              <td>
                <%= link_to "削除",admin_comment_path(comment), method: :delete, data: {confirm: "本当に削除しますか？"}, class: "btn btn-danger btn-sm fs-5" %>
              </td>
            </tr>
          <% end %>
        <tbody>
      </table>
    </div>
  </div>
  <div class="row justify-content-md-center">
    <div class="col-auto">
      <%= paginate @comments %>
    </div>
  </div>
</div>