config/routes.rb
Rails.application.routes.draw do



  namespace :admin do
    get 'tags/new'
  end
  devise_for :anglers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_scope :angler do
    post 'public/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end
  

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    root to: 'homes#top'
    resources :fishing_successes, only: [:index, :show, :destroy]
    resources :anglers, only: [:index, :show, :destroy]
    resources :comments, only: [:destroy]
    resources :tags, only: [:new, :create, :destroy]
  end


  scope module: :public do
    root to: 'homes#top'
    get 'search'=>'fishing_successes#search'
    resources :fishing_successes, only: [:index, :show, :new, :create, :destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    get 'anglers/favorites'=>'anglers#my_favorite'
    get 'anglers/fishing_successes'=>'anglers#my_post'
    get 'anglers/mypage'=>"anglers#show"
    get 'anglers/information/edit'=>"anglers#edit"
    get 'anglers/withdrawal/verification'=>"anglers#verification"
    patch 'anglers/information'=>"anglers#update"
    delete 'anglers/withdrawal'=>"anglers#destroy"
  end

end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :fishing_success_tags, dependent: :destroy
  has_many :fishing_successes, through: :fishing_success_tags
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController
  def new
    @tags = Tag.all
    @tag = Tag.new
  end

  def create
    tag = Tag.new(tag_params)
    tag.save
    redirect_to request.referer
  end

  def destroy
    Tag.find(params[:id]).destroy
    redirect_to request.referer
  end

  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/views/admin/tags/new.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="col">
        <h3>タグ追加</h3>
      </div>
    </div>
    <div class="row">
      <%= form_with model: @tag, local: true, url: admin_tags_path, method: :post do |f| %>
        <%= f.text_field :name %>
        <%= f.submit "追加" %>
      <% end %>
    </div>
    <div class="row">
      <% @tags.each do |tag| %>
        <div class="col-4 my-2">
          <div class="row">
            <div class="col-auto">
              <%= link_to "削除",admin_tag_path(tag), method: :delete, data: {confirm: "本当に削除しますか？"}, class: "btn btn-sm btn-danger" %>
            </div>
            <div class="col-2"><%= tag.id %></div>
            <div class="col"><%= tag.name %></div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</main>