config/routes.rb
Rails.application.routes.draw do



  namespace :admin do
    get 'tags/new'
  end
  devise_for :anglers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_scope :angler do
    post 'public/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end
  

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    root to: 'homes#top'
    resources :fishing_successes, only: [:index, :show, :destroy]
    resources :anglers, only: [:index, :show, :destroy]
    resources :comments, only: [:destroy]
    resources :tags, only: [:new, :create, :destroy]
  end


  scope module: :public do
    root to: 'homes#top'
    get 'search'=>'fishing_successes#search'
    resources :fishing_successes, only: [:index, :show, :new, :create, :destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    get 'anglers/favorites'=>'anglers#my_favorite'
    get 'anglers/fishing_successes'=>'anglers#my_post'
    get 'anglers/mypage'=>"anglers#show"
    get 'anglers/information/edit'=>"anglers#edit"
    get 'anglers/withdrawal/verification'=>"anglers#verification"
    patch 'anglers/information'=>"anglers#update"
    delete 'anglers/withdrawal'=>"anglers#destroy"
  end

end

app/controllers/admin/fishing_successes_controller.rb
class Admin::FishingSuccessesController < ApplicationController
  before_action :authenticate_admin!
  def index
    @fishing_successes = FishingSuccess.page(params[:page]).per(10).order(created_at: :desc)
  end

  def show
    @fishing_success = FishingSuccess.find(params[:id])
  end

  def destroy
    FishingSuccess.find(params[:id]).destroy
    redirect_to admin_fishing_successes_path
  end

  def fishing_success_params
      params.require(:fishing_success).permit(:angler_id, :fishing_day, :tackle, :method, :fishing_spot, :lng, :lat, :situation, tag_ids: [])
  end
end

app/helpers/admin/fishing_successes_helper.rb
module Admin::FishingSuccessesHelper
end

app/views/admin/fishing_successes/index.html.erb
<div class="container">
  <div class="row my-4">
    <div class="col text-center mt-3 fs-4">
      投稿一覧
    </div>
  </div>
  <div class="row justify-content-center mx-5">
    <div class="col-8">
      <table class="table table-hover table-inverse" width="100%">
        <thead class="table-secondary">
          <tr>
            <th width="20%">釣行日</th>
            <th width="20%">投稿画像</th>
            <th width="40%">氏名</th>
            <th width="20%">投稿日時</th>
          </tr>
        </thead>
        <tbody>
          <% @fishing_successes.each do |fishing_success| %>
            <tr>
              <td>
                <%= fishing_success.fishing_day.strftime('%m月%d日') %>
              </td>
              <td>
                <%= link_to admin_fishing_success_path(fishing_success), class: "link" do %>
                  <%= image_tag fishing_success.get_image, :size =>'50x30' %>
                <% end %>
              </td>
              <td>
                <%= fishing_success.angler.name %>
              </td>
              <td  style="color: #999999;">
                <%= fishing_success.created_at.strftime('%m月%d日') %>
              </td>
            </tr>
          <% end %>
        <tbody>
      </table>
    </div>
  </div>
  <div class="row justify-content-md-center">
    <div class="col-auto">
      <%= paginate @fishing_successes %>
    </div>
  </div>
</div>

app/views/admin/fishing_successes/show.html.erb
<main>
  <div class="container">
    <div class="row my-2">
      <div class=" text-center mt-3 fs-4">
        釣果詳細
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="col-7">
        <%= link_to admin_angler_path(@fishing_success.angler), class: "link" do %>
          <div class="row justify-content-center rounded-top border border-dark" style="background-color: #F5F5F5;">
            <div class="col text-center my-2">
              <%= image_tag @fishing_success.angler.get_profile_image(30,30), class: "rounded-circle" %>
              <%= @fishing_success.angler.name %>
            </div>
          </div>
        <% end %>
        <div class="row border-right border-left border-dark" style="background-color: #F5F5F5;">
          <div class="col px-3">
            <%= @fishing_success.fishing_day.strftime("%m月%d日の釣果")  %>
          </div>
          <div class="col px-3">
            釣れた場所
          </div>
        </div>
        <div class="row border-right border-left border-dark" style="background-color: #F5F5F5;">
          <div class="col px-3">
            <div class="row">
              <div class="col">
                <%= image_tag @fishing_success.get_image, :size =>'300x250' %>
              </div>
            </div>
          </div>
          <div class="col px-3">

            <div id='map'></div>

            <style>
            #map {
              height: 300px;
              width: 100%;
            }
            </style>

            <script>
            let map
            let marker
            function initMap(){
              geocoder = new google.maps.Geocoder()

              map = new google.maps.Map(document.getElementById('map'), {
                center:  {lat: <%= @fishing_success.lat %>, lng: <%= @fishing_success.lng %>},
                zoom: 15,
              });

              marker = new google.maps.Marker({
                position:  {lat: <%= @fishing_success.lat %>, lng: <%= @fishing_success.lng %>},
                map: map
              });
            }

            </script>
            <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['API_KEY']%>&callback=initMap" async defer></script>

          </div>
        </div>
        <div class="row border-right border-left border-dark px-3 py-3" style="background-color: #F5F5F5;">
          <div class="col">
            <table width="100%">
              <tr class="border-bottom border-dark">
                <th>釣果</th>
                <td class="pt-3">
                  <% @fishing_success.tags.each do |tag| %>
                    <%= tag.name %>
                  <% end %>
                </td>
              </tr>
              <tr class="border-bottom border-dark">
                <th class="pt-3">タックル</th>
                <td class="pt-3"><%= @fishing_success.tackle %></td>
              </tr>
              <tr class="border-bottom border-dark">
                <th class="pt-3">釣り方</th>
                <td class="pt-3"><%= @fishing_success.method %></td>
              </tr>
            </table>
          </div>
          <div class="col">
            <div class="row px-3">
              <div class="col">
                投稿者からの情報！
              </div>
            </div>
            <div class="row px-3">
              <div class="col bg-white rounded border border-dark scr" style="height: 80px;">
                <%= @fishing_success.situation %>
              </div>
            </div>
          </div>
        </div>
        <div class="row rounded-bottom border-right border-left border-bottom border-dark py-3 mb-3" style="background-color: #F5F5F5;">
          <div class="col text-center">
            <%= link_to "投稿を削除",admin_fishing_success_path(@fishing_success), method: :delete, data: {confirm: "本当に削除しますか？"}, class: "btn btn-danger btn-sm fs-5" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>