config/routes.rb
Rails.application.routes.draw do



  namespace :admin do
    get 'tags/new'
  end
  devise_for :anglers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_scope :angler do
    post 'public/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end
  

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    root to: 'homes#top'
    resources :fishing_successes, only: [:index, :show, :destroy]
    resources :anglers, only: [:index, :show, :destroy]
    resources :comments, only: [:destroy]
    resources :tags, only: [:new, :create, :destroy]
  end


  scope module: :public do
    root to: 'homes#top'
    get 'search'=>'fishing_successes#search'
    resources :fishing_successes, only: [:index, :show, :new, :create, :destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    get 'anglers/favorites'=>'anglers#my_favorite'
    get 'anglers/fishing_successes'=>'anglers#my_post'
    get 'anglers/mypage'=>"anglers#show"
    get 'anglers/information/edit'=>"anglers#edit"
    get 'anglers/withdrawal/verification'=>"anglers#verification"
    patch 'anglers/information'=>"anglers#update"
    delete 'anglers/withdrawal'=>"anglers#destroy"
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
end

app/models/angler.rb
class Angler < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: { maximum: 10 }
  validates :email, presence: true
  validates :password, presence: true, on: :create
  validates :password_confirmation, presence: true, on: :create

  has_many :fishing_successes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_one_attached :profile_image

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |angler|
      angler.password = SecureRandom.urlsafe_base64
      angler.name = "ゲスト"
    end
  end

  def get_profile_image(width,height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width,height]).processed
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :angler
  belongs_to :fishing_success

  validates :content, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :angler
  belongs_to :fishing_success
end

app/models/fishing_success.rb
class FishingSuccess < ApplicationRecord
  belongs_to :angler
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :fishing_success_tags, dependent: :destroy
  has_many :tags, through: :fishing_success_tags
  has_one_attached :image

  validates :image, presence: true
  validates :fishing_day, presence: true
  validates :tag_ids, presence: true
  validates :fishing_spot, presence: true
  validates :lng, presence: true
  validates :lat, presence: true





  def favorited_by?(angler)
    favorites.exists?(angler_id: angler.id)
  end

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

  def self.search(keyword)
    where(["method like? OR tackle like?", "%#{keyword}%", "%#{keyword}%"])
  end

  enum fishing_spot:{
     北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
     茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
     新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
     岐阜県:21,静岡県:22,愛知県:23,三重県:24,
     滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
     鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
     徳島県:36,香川県:37,愛媛県:38,高知県:39,
     福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,
     沖縄県:47
   }

end

app/models/fishing_success_tag.rb
class FishingSuccessTag < ApplicationRecord
  belongs_to :tag
  belongs_to :fishing_success
  
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :fishing_success_tags, dependent: :destroy
  has_many :fishing_successes, through: :fishing_success_tags
end

app/controllers/admin/anglers_controller.rb
class Admin::AnglersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @anglers = Angler.page(params[:page]).per(10).order(created_at: :desc)
  end

  def show
    @angler = Angler.find(params[:id])
  end

  def destroy
    Angler.find(params[:id]).destroy
    redirect_to admin_anglers_path
  end

  def angler_params
      params.require(:angler).permit(:name, :introduction, :imag)
  end
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  before_action :authenticate_admin!

  def destroy
    Comment.find(params[:id]).destroy
    redirect_to admin_root_path
  end

  def comment_params
      params.require(:comment).permit(:angler_id, :fishing_success_id, :content)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
    @comments = Comment.page(params[:page]).per(10).order(created_at: :desc)
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  def after_sign_in_path_for(resource)
    admin_root_path
  end
  
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController
  def new
    @tags = Tag.all
    @tag = Tag.new
  end

  def create
    tag = Tag.new(tag_params)
    tag.save
    redirect_to request.referer
  end

  def destroy
    Tag.find(params[:id]).destroy
    redirect_to request.referer
  end

  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :angler
        root_path
    elsif resource_or_scope == :admin
        new_admin_session_path
    end
  end
end

app/helpers/admin/anglers_helper.rb
module Admin::AnglersHelper
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoFishing</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>


    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" >
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" ></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
  </head>

  <body>
    <% if request.fullpath.include? "/admin" %>
      <% if admin_signed_in? %>
        <header>
          <nav class="navbar navbar-expand-lg navbar-light border-bottom border-dark" style="background-color: #004C99;">
            <div class="container-fluid">
              <div clas="col-auto bg-light border navbar-brand">
                <%= image_tag src="rogo6.jpg", size: "200x80" %>
              </div>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav ml-auto">
                  <li class="pr-3">
                    <%= link_to admin_anglers_path, class: "btn btn-secondary" do %>
                      会員一覧
                    <% end %>
                  </li>
                  <li class="pr-3 pl-3">
                    <%= link_to admin_fishing_successes_path, class: "btn btn-secondary" do %>
                      投稿一覧
                    <% end %>
                  </li>
                  <li class="pr-3 pl-3">
                    <%= link_to admin_root_path, class: "btn btn-secondary" do %>
                      コメント一覧
                    <% end %>
                  </li>
                  <li class="pr-3 pl-3">
                    <%= link_to new_admin_tag_path, class: "btn btn-secondary" do %>
                      タグ追加
                    <% end %>
                  </li>
                  <li class="pl-3">
                    <%= link_to destroy_admin_session_path, method: :delete, class: "btn btn-secondary" do %>
                      ログアウト
                    <% end %>
                  </li>
                </ul>
              </div>
            </div>
          </nav>
        </header>
      <% else%>
        <header>
          <div class="container-fluid border-bottom border-dark" style="background-color: #004C99;">
            <div clas="col">
              <%= image_tag src="rogo6.jpg", size: "200x80" %>
            </div>
          </div>
        </header>
      <% end %>
    <% else %>
      <% if angler_signed_in? %>
        <header>
          <nav class="navbar navbar-expand-lg navbar-light border-bottom border-dark" style="background-color: #004C99;">
            <div class="container-fluid">
              <div clas="col-auto bg-light border">
                <%= link_to root_path, class: "navbar-brand" do %>
                  <%= image_tag src="rogo6.jpg", size: "200x80" %>
                <% end %>
              </div>
              <div clas="col">
                <div class="row">
                  <div class="col text-center pb-4 text-light">
                    ようこそ、<%= current_angler.name %>！
                  </div>
                </div>
                <div class="row">
                  <div class="col text-center">
                    <%= form_with model: FishingSuccess, url: search_path, method: :get, local: true do |f| %>
                      <%= f.text_field :keyword, value: @keyword, style: "width: 300px" %>
                      <%= f.submit "検索" %>
                    <% end %>
                  </div>
                </div>
              </div>
              <div clas="col-auto">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                  <ul class="navbar-nav">
                    <li class="pl-3">
                      <%= link_to root_path, class: "btn btn-secondary" do %>
                        トップ
                      <% end %>
                    </li>
                    <li class="pl-3">
                      <%= link_to destroy_angler_session_path, method: :delete, class: "btn btn-secondary" do %>
                        ログアウト
                      <% end %>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </nav>
        </header>
      <% else %>
        <header>
          <nav class="navbar navbar-expand-lg navbar-light border-bottom border-dark" style="background-color: #004C99;">
            <div class="container-fluid pt-4 pb-4">
              <div clas="col-auto bg-light border">
                <%= link_to root_path, class: "navbar-brand" do %>
                  <%= image_tag src="rogo6.jpg", size: "200x80" %>
                <% end %>
              </div>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav ml-auto">
                  <li class="nav-item px-1 py-1">
                    <%= link_to root_path, class: "btn btn-secondary" do %>
                      トップ
                    <% end %>
                  </li>
                  <li class="nav-item px-1 py-1">
                    <%= link_to new_angler_registration_path, class: "btn btn-secondary" do %>
                      新規登録
                    <% end %>
                  </li>
                  <li class="nav-item px-1 py-1">
                    <%= link_to new_angler_session_path, class: "btn btn-secondary" do %>
                      ログイン
                    <% end %>
                  </li>
                </ul>
              </div>
            </div>
          </nav>
        </header>
      <% end %>
    <% end %>
    <%= yield %>
  </body>
</html>